module.exports = [
    {rating: 0, gradeAvg: 0.80, online: true,  credits: 3, num: '8803-O01',  foundational: false, department: 'CS',  name: 'Artificial Intelligence for Robotics'}, // erroneous GT docs have this listed
    {rating: 2, gradeAvg: 0.89, online: true,  credits: 3, num: '6250',      foundational: true,  department: 'CS',  name: 'Computer Networks'},
    {rating: 2, gradeAvg: 0.89, online: true,  credits: 3, num: '6300',      foundational: true,  department: 'CS',  name: 'Software Development Process'},
    {rating: 0, gradeAvg: 0.79, online: true,  credits: 3, num: '6310',      foundational: true,  department: 'CS',  name: 'Software Architecture and Design'},
    {rating: 1, gradeAvg: 0.89, online: true,  credits: 3, num: '6340',      foundational: false, department: 'CS',  name: 'Software Analysis and Testing'},
    {rating: 1, gradeAvg: 0.80, online: true,  credits: 3, num: '6475',      foundational: false, department: 'CS',  name: 'Computational Photography'},
    {rating: 0, gradeAvg: 0.78, online: true,  credits: 3, num: '7637',      foundational: true,  department: 'CS',  name: 'Knowledge-Based Artificial Intelligence: Cognitive Systems'},
    {rating: 2, gradeAvg: 0.89, online: true,  credits: 3, num: '6440',      foundational: false, department: 'CS',  name: 'Intro to Health Informatics'},
    {rating: 0, gradeAvg: 0.80, online: true,  credits: 3, num: '8803-BDHI', foundational: false, department: 'CSE', name: 'Special Topics: Big Data for Health Informatics'},
    {rating: 1, gradeAvg: 0.81, online: true,  credits: 3, num: '8803-002',  foundational: true,  department: 'CS',  name: 'Introduction to Operating Systems'},
    {rating: 1, gradeAvg: 0.83, online: true,  credits: 3, num: '6262',      foundational: false, department: 'CS',  name: 'Network Security'},
    {rating: 3, gradeAvg: 0.90, online: true,  credits: 3, num: '6035',      foundational: false, department: 'CS',  name: 'Introduction to Information Security'},
    {rating: 1, gradeAvg: 0.85, online: true,  credits: 3, num: '6400',      foundational: false, department: 'CS',  name: 'Database Systems Concepts and Design'},
    {rating: 1, gradeAvg: 0.83, online: true,  credits: 3, num: '6601',      foundational: false, department: 'CS',  name: 'Artificial Intelligence'},
    {rating: 0, gradeAvg: 0.77, online: true,  credits: 3, num: '6290',      foundational: true,  department: 'CS',  name: 'High Performance Computer Architecture'},
    {rating: 1, gradeAvg: 0.81, online: true,  credits: 3, num: '8803-RL',   foundational: false, department: 'CS',  name: 'Special Topics: Reinforcement Learning'},
    {rating: 2, gradeAvg: 0.88, online: true,  credits: 3, num: '6460',      foundational: false, department: 'CS',  name: 'Educational Technology: Conceptual Foundations'},
    {rating: 0, gradeAvg: 0.75, online: true,  credits: 3, num: '6210',      foundational: true,  department: 'CS',  name: 'Advanced Operating Systems'},
    {rating: 5, gradeAvg: 0.98, online: true,  credits: 3, num: '6465',      foundational: false, department: 'CS',  name: 'Computational Journalism'},
    {rating: 3, gradeAvg: 0.90, online: true,  credits: 3, num: '7646',      foundational: false, department: 'CS',  name: 'Machine Learning for Trading'},
    {rating: 0, gradeAvg: 0.74, online: true,  credits: 3, num: '6220',      foundational: true,  department: 'CSE', name: 'Intro to High-Performance Computing'},
    {rating: 4, gradeAvg: 0.91, online: true,  credits: 3, num: '6242',      foundational: false, department: 'CSE', name: 'Data and Visual Analytics'},
    {rating: 1, gradeAvg: 0.80, online: true,  credits: 3, num: '7641',      foundational: true,  department: 'CS',  name: 'Machine Learning'},
    {rating: 0, gradeAvg: 0.79, online: true,  credits: 3, num: '6505',      foundational: true,  department: 'CS',  name: 'Computability, Complexity and Algorithms'},
    {rating: 3, gradeAvg: 0.91, online: false, credits: 3, num: '7210',      foundational: false, department: 'CS',  name: 'Distributed Computing'},
    {rating: 3, gradeAvg: 0.90, online: false, credits: 3, num: '7260',      foundational: false, department: 'CS',  name: 'Internetworking Architectures and Protocols'},
    {rating: 2, gradeAvg: 0.87, online: false, credits: 3, num: '7630',      foundational: false, department: 'CS',  name: 'Autonomous Robotics'},
    {rating: 0, gradeAvg: 0.77, online: false, credits: 3, num: '6740',      foundational: false, department: 'CS',  name: 'Computational Data Analysis: Learning, Mining, and Computation'},
    {rating: 0, gradeAvg: 0.73, online: false, credits: 3, num: '6260',      foundational: false, department: 'CS',  name: 'Applied Cryptography'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-HTPC', foundational: false, department: 'CS',  name: 'Special Topics: Hot Topics in Parallel Computing'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-PNA',  foundational: false, department: 'CS',  name: 'Special Topics: Parallel Numerical Algorithms'},
    {rating: 5, gradeAvg: 0.97, online: false, credits: 3, num: '6675',      foundational: false, department: 'CS',  name: 'Advanced Internet Computing Systems and Applications'},
    {rating: 2, gradeAvg: 0.87, online: false, credits: 3, num: '7290',      foundational: false, department: 'CS',  name: 'Advanced Topics in Microarchitecture'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-MGCV', foundational: false, department: 'CS',  name: 'Special Topics: Multiview Geometry in Computer Vision'},
    {rating: 4, gradeAvg: 0.91, online: false, credits: 3, num: '7270',      foundational: false, department: 'CS',  name: 'Networked Applications and Services'},
    {rating: 0, gradeAvg: 0.74, online: false, credits: 3, num: '7616',      foundational: false, department: 'CS',  name: 'Pattern Recognition'},
    {rating: 5, gradeAvg: 1.00, online: false, credits: 3, num: '7292',      foundational: false, department: 'CS',  name: 'Reliability and Security in Computer Architecture'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-FPL',  foundational: false, department: 'CS',  name: 'Special Topics: Foundations of Programming Languages'},
    {rating: 0, gradeAvg: 0.69, online: false, credits: 3, num: '7560',      foundational: false, department: 'CS',  name: 'Theory of Cryptography'},
    {rating: 1, gradeAvg: 0.80, online: false, credits: 3, num: '6520',      foundational: false, department: 'CS',  name: 'Computational Complexity Theory'},
    {rating: 0, gradeAvg: 0.79, online: false, credits: 3, num: '7520',      foundational: false, department: 'CS',  name: 'Approximation Algorithms'},
    {rating: 2, gradeAvg: 0.89, online: false, credits: 3, num: '7631',      foundational: false, department: 'CS',  name: 'Autonomous Multi-Robot Systems'},
    {rating: 3, gradeAvg: 0.95, online: false, credits: 3, num: '7633',      foundational: false, department: 'CS',  name: 'Human-Robot Interaction'},
    {rating: 5, gradeAvg: 0.95, online: false, credits: 3, num: '7649',      foundational: false, department: 'CS',  name: 'Robot Intelligence: Planning'},
    {rating: 2, gradeAvg: 0.86, online: false, credits: 3, num: '6236',      foundational: false, department: 'CS',  name: 'Parallel and Distributed Simulation'},
    {rating: 0, gradeAvg: 0.75, online: false, credits: 3, num: '7650',      foundational: false, department: 'CS',  name: 'Natural Language'},
    {rating: 0, gradeAvg: 0.71, online: false, credits: 3, num: '7545',      foundational: false, department: 'CS',  name: 'Machine Learning Theory'},
    {rating: 4, gradeAvg: 0.91, online: false, credits: 3, num: '7495',      foundational: false, department: 'CS',  name: 'Computer Vision'},
    {rating: 1, gradeAvg: 0.80, online: false, credits: 3, num: '6238',      foundational: false, department: 'CS',  name: 'Secure Computer Systems'},
    {rating: 0, gradeAvg: 0.79, online: false, credits: 3, num: '6230',      foundational: false, department: 'CS',  name: 'High-Performance Parallel Computing: Tools and Applications'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-PGM',  foundational: false, department: 'CS',  name: 'Special Topics: Probabilistic Graph Models'},
    {rating: 2, gradeAvg: 0.87, online: false, credits: 3, num: '7530',      foundational: false, department: 'CS',  name: 'Randomized Algorithms'},
    {rating: 2, gradeAvg: 0.89, online: false, credits: 3, num: '6365',      foundational: false, department: 'CS',  name: 'Introduction to Enterprise Computing'},
    {rating: 1, gradeAvg: 0.80, online: false, credits: 3, num: '7636',      foundational: false, department: 'CS',  name: 'Computational Perception'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-CC',   foundational: false, department: 'CS',  name: 'Special Topics: Computational Creativity'},
    {rating: 0, gradeAvg: 0.80, online: false, credits: 3, num: '6221',      foundational: false, department: 'CS',  name: 'Multicore Computing: Concurrency and Parallelism on the Desktop'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-CSS',  foundational: false, department: 'CS',  name: 'Special Topics: Computational Social Science'},
    {rating: 2, gradeAvg: 0.86, online: false, credits: 3, num: '7610',      foundational: false, department: 'CS',  name: 'Modeling and Design'},
    {rating: 2, gradeAvg: 0.87, online: false, credits: 3, num: '7634',      foundational: false, department: 'CS',  name: 'AI Storytelling in Virtual Worlds'},
    {rating: 1, gradeAvg: 0.81, online: false, credits: 3, num: '8803-AGA',  foundational: false, department: 'CS',  name: 'Special Topics: Advanced Game AI'},
    {rating: 1, gradeAvg: 0.84, online: false, credits: 3, num: '7632',      foundational: false, department: 'CS',  name: 'Game AI'},
    {rating: 1, gradeAvg: 0.80, online: false, credits: 3, num: '6795',      foundational: false, department: 'CS',  name: 'Introduction to Cognitive Science'},
    {rating: 0, gradeAvg: 0.62, online: false, credits: 3, num: '7540',      foundational: false, department: 'CS',  name: 'Spectral Algorithms'},
    {rating: 0, gradeAvg: 0.78, online: false, credits: 3, num: '6550',      foundational: false, department: 'CS',  name: 'Design and Analysis of Algorithms'},
    {rating: 5, gradeAvg: 0.95, online: false, credits: 3, num: '6422',      foundational: false, department: 'CS',  name: 'Database System Implementation'},
    {rating: 1, gradeAvg: 0.82, online: false, credits: 3, num: '7510',      foundational: false, department: 'CSE', name: 'Graph Algorithms'},
    {rating: 0, gradeAvg: 0.74, online: false, credits: 3, num: '6241',      foundational: false, department: 'CS',  name: 'Compiler Design'},
    {rating: 5, gradeAvg: 0.96, online: false, credits: 3, num: '7620',      foundational: false, department: 'CS',  name: 'Case-Based Reasoning'},
    {rating: 2, gradeAvg: 0.87, online: false, credits: 3, num: '6240',      foundational: false, department: 'CSE', name: 'Web Search and Text Mining'},
    {rating: 1, gradeAvg: 0.82, online: false, credits: 3, num: '6140',      foundational: false, department: 'CSE', name: 'Computational Science and Engineering Algorithms'},
    {rating: 0, gradeAvg: 0.00, online: false, credits: 3, num: '7499',      foundational: false, department: 'CS',  name: '3D Reconstruction'}, // NOT AVAILABLE
    // {rating: -1e3, gradeAvg: 0.00, online:  credits: 3,true, num: '4495', foundational: true, department: 'CS', name: 'Computer Vision'}, // listed as a grad course and undergrad course
    // CS 8803 Special Topics: Data Visualization
    // CS 8803 Special Topics: Biomedical Analytics
    // CS 8803 Special Topics: Embedded Software
];