module.exports = [
    {rating: 5, num: '6250', foundational: true, department: 'CS', name: 'Computer Networks', credits: 3},
    {rating: 5, num: '6300', foundational: true, department: 'CS', name: 'Software Development Process', credits: 3},
    {rating: 5, num: '6310', foundational: true, department: 'CS', name: 'Software Architecture and Design', credits: 3},
    {rating: 5, num: '6340', foundational: false, department: 'CS', name: 'Software Analysis and Testing', credits: 3},
    {rating: 5, num: '6475', foundational: false, department: 'CS', name: 'Computational Photography', credits: 3},
    {rating: 5, num: '7637', foundational: true, department: 'CS', name: 'Knowledge-Based Artificial Intelligence: Cognitive Systems', credits: 3},
    {rating: 5, num: '6440', foundational: false, department: 'CS', name: 'Intro to Health Informatics', credits: 3},
    {rating: 5, num: '8803-BDHI', foundational: false, department: 'CSE', name: 'Special Topics: Big Data for Health Informatics', credits: 3},
    {rating: 5, num: '7210', foundational: false, department: 'CS', name: 'Distributed Computing', credits: 3},
    {rating: 4, num: '7260', foundational: false, department: 'CS', name: 'Internetworking Architectures and Protocols', credits: 3},
    {rating: 3, num: '8803-MGCV', foundational: false, department: 'CS', name: 'Special Topics: Multiview Geometry in Computer Vision', credits: 3},
    {rating: 3, num: '7499', foundational: false, department: 'CS', name: '3D Reconstruction', credits: 3},
    {rating: 1, num: '6260', foundational: false, department: 'CS', name: 'Applied Cryptography', credits: 3},
    {rating: 1, num: '8803-HTPC', foundational: false, department: 'CS', name: 'Special Topics: Hot Topics in Parallel Computing', credits: 3},
    {rating: 1, num: '8803-002', foundational: true, department: 'CS', name: 'Introduction to Operating Systems', credits: 3},
    {rating: 1, num: '8803-PNA', foundational: false, department: 'CS', name: 'Special Topics: Parallel Numerical Algorithms', credits: 3},
    {rating: 1, num: '6675', foundational: false, department: 'CS', name: 'Advanced Internet Computing Systems and Applications', credits: 3},
    {rating: 1, num: '7290', foundational: false, department: 'CS', name: 'Advanced Topics in Microarchitecture', credits: 3},
    {rating: 1, num: '7270', foundational: false, department: 'CS', name: 'Networked Applications and Services', credits: 3},
    {rating: 1, num: '6262', foundational: false, department: 'CS', name: 'Network Security', credits: 3},
    {rating: 1, num: '7616', foundational: false, department: 'CS', name: 'Pattern Recognition', credits: 3},
    {rating: 1, num: '7292', foundational: false, department: 'CS', name: 'Reliability and Security in Computer Architecture', credits: 3},
    {rating: 1, num: '8803-FPL', foundational: false, department: 'CS', name: 'Special Topics: Foundations of Programming Languages', credits: 3},
    {rating: 1, num: '7560', foundational: false, department: 'CS', name: 'Theory of Cryptography', credits: 3},
    {rating: 1, num: '6520', foundational: false, department: 'CS', name: 'Computational Complexity Theory', credits: 3},
    {rating: 1, num: '7520', foundational: false, department: 'CS', name: 'Approximation Algorithms', credits: 3},
    {rating: 1, num: '6035', foundational: false, department: 'CS', name: 'Introduction to Information Security', credits: 3},
    {rating: 3, num: '7630', foundational: false, department: 'CS', name: 'Autonomous Robotics', credits: 3},
    {rating: 1, num: '7631', foundational: false, department: 'CS', name: 'Autonomous Multi-Robot Systems', credits: 3},
    {rating: 1, num: '7633', foundational: false, department: 'CS', name: 'Human-Robot Interaction', credits: 3},
    {rating: 1, num: '7649', foundational: false, department: 'CS', name: 'Robot Intelligence: Planning', credits: 3},
    {rating: 1, num: '8803-O01', foundational: false, department: 'CS', name: 'Artificial Intelligence for Robotics', credits: 3}, // erroneous GT docs have this listed
    {rating: 1, num: '6236', foundational: false, department: 'CS', name: 'Parallel and Distributed Simulation', credits: 3},
    {rating: 3, num: '6400', foundational: false, department: 'CS', name: 'Database Systems Concepts and Design', credits: 3},
    {rating: 1, num: '7650', foundational: false, department: 'CS', name: 'Natural Language', credits: 3},
    {rating: 1, num: '7545', foundational: false, department: 'CS', name: 'Machine Learning Theory', credits: 3},
    {rating: 2, num: '6740', foundational: false, department: 'CS', name: 'Computational Data Analysis: Learning, Mining, and Computation', credits: 3},
    {rating: 4, num: '7495', foundational: false, department: 'CS', name: 'Computer Vision', credits: 3},
    {rating: 1, num: '6238', foundational: false, department: 'CS', name: 'Secure Computer Systems', credits: 3},
    {rating: 1, num: '6230', foundational: false, department: 'CS', name: 'High-Performance Parallel Computing: Tools and Applications', credits: 3},
    {rating: 1, num: '8803-PGM', foundational: false, department: 'CS', name: 'Special Topics: Probabilistic Graph Models', credits: 3},
    {rating: 0, num: '6140', foundational: false, department: 'CSE', name: 'Computational Science and Engineering Algorithms', credits: 3},
    {rating: 1, num: '7530', foundational: false, department: 'CS', name: 'Randomized Algorithms', credits: 3},
    {rating: 1, num: '6601', foundational: false, department: 'CS', name: 'Artificial Intelligence', credits: 3},
    {rating: 1, num: '6290', foundational: true, department: 'CS', name: 'High Performance Computer Architecture', credits: 3},
    {rating: 1, num: '6365', foundational: false, department: 'CS', name: 'Introduction to Enterprise Computing', credits: 3},
    {rating: 1, num: '8803-RL', foundational: false, department: 'CS', name: 'Special Topics: Reinforcement Learning', credits: 3},
    {rating: 0, num: '6505', foundational: true, department: 'CS', name: 'Computability, Complexity and Algorithms', credits: 3},
    {rating: 1, num: '7636', foundational: false, department: 'CS', name: 'Computational Perception', credits: 3},
    {rating: 1, num: '8803-CC', foundational: false, department: 'CS', name: 'Special Topics: Computational Creativity', credits: 3},
    {rating: 1, num: '6221', foundational: false, department: 'CS', name: 'Multicore Computing: Concurrency and Parallelism on the Desktop', credits: 3},
    {rating: 1, num: '8803-CSS', foundational: false, department: 'CS', name: 'Special Topics: Computational Social Science', credits: 3},
    {rating: 1, num: '6460', foundational: false, department: 'CS', name: 'Educational Technology: Conceptual Foundations', credits: 3},
    {rating: 1, num: '7610', foundational: false, department: 'CS', name: 'Modeling and Design', credits: 3},
    {rating: 1, num: '6210', foundational: true, department: 'CS', name: 'Advanced Operating Systems', credits: 3},
    {rating: 1, num: '6465', foundational: false, department: 'CS', name: 'Computational Journalism', credits: 3},
    {rating: 1, num: '7634', foundational: false, department: 'CS', name: 'AI Storytelling in Virtual Worlds', credits: 3},
    {rating: 1, num: '8803-AGA', foundational: false, department: 'CS', name: 'Special Topics: Advanced Game AI', credits: 3},
    {rating: 1, num: '7632', foundational: false, department: 'CS', name: 'Game AI', credits: 3},
    {rating: 1, num: '6795', foundational: false, department: 'CS', name: 'Introduction to Cognitive Science', credits: 3},
    {rating: 1, num: '7646', foundational: false, department: 'CS', name: 'Machine Learning for Trading', credits: 3},
    {rating: 1, num: '7540', foundational: false, department: 'CS', name: 'Spectral Algorithms', credits: 3},
    {rating: 1, num: '6550', foundational: false, department: 'CS', name: 'Design and Analysis of Algorithms', credits: 3},
    {rating: 1, num: '6422', foundational: false, department: 'CS', name: 'Database System Implementation', credits: 3},
    {rating: 1, num: '7510', foundational: false, department: 'CSE', name: 'Graph Algorithms', credits: 3},
    {rating: 1, num: '6241', foundational: false, department: 'CS', name: 'Compiler Design', credits: 3},
    {rating: 1, num: '7620', foundational: false, department: 'CS', name: 'Case-Based Reasoning', credits: 3},
    {rating: 1, num: '6220', foundational: true, department: 'CSE', name: 'Intro to High-Performance Computing', credits: 3},
    {rating: 1, num: '6242', foundational: false, department: 'CSE', name: 'Data and Visual Analytics', credits: 3},
    {rating: 1, num: '7641', foundational: true, department: 'CS', name: 'Machine Learning', credits: 3},
    {rating: 1, num: '6240', foundational: false, department: 'CSE', name: 'Web Search and Text Mining', credits: 3}
    // {rating: 1, num: '4495', foundational: true, department: 'CS', name: 'Computer Vision', credits: 3}, // listed as a grad course and undergrad course
];